export {
  AUTHORABLE_RELATION_TYPES,
  bodyBridgeEnvelopeSchema,
  createBodylessResource,
  createEdge,
  createTextResourceWithBody,
  deleteEdge,
  reconcileBodyBridge,
  renameResource,
  tagResource,
  type AuthorableRelationType,
  type BodylessKind,
  type CreateBodylessResourceDeps,
  type CreateBodylessResourceInput,
  type CreateBodylessResourceResult,
  type CreateEdgeInput,
  type CreateTextResourceDeps,
  type CreateTextResourceInput,
  type CreateTextResourceResult,
  type DeleteEdgeInput,
  type FanoutEdgeInput,
  type InsertEdgeInput,
  type ParentFolderPlacement,
  type ReconcileDeps,
  type ReconcileResult,
  type RenameResourceInput,
  type TagResourceInput,
} from './text-resource.fanout';
export {
  incrementResourceViewCount,
  setResourceDescription,
  setResourceLink,
  setResourceMediaMeta,
  setResourceProvenance,
  type IncrementResourceViewCountInput,
  type KbAttributeDeps,
  type SetResourceDescriptionInput,
  type SetResourceLinkInput,
  type SetResourceMediaMetaInput,
  type SetResourceProvenanceInput,
} from './kb-attribute.fanout';
export {
  SAMPLE_ROOT_TITLE,
  SampleAlreadySeededError,
  seedSampleKnowledgeGraph,
  type SeedSampleDeps,
  type SeedSampleResult,
} from './sample-knowledge-graph.builder';
